name: 자동배포2

on:
  push:
    tags:
      - v.*.message

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo '::set-output ${GITHUB_REF}'

      - name: check tag names test
        run: echo ${{ github.event.ref }}

      - name: check tag names2
        if: ${{ !endsWith(github.event.ref, 'message') }}
        run: exit 2

      - name: check tag names1
        if: "!endsWith(github.event.ref, 'message')"
        run: echo 'test1 !! false'
