name: 빌드 테스트

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo '::set-output endsWith(github.ref, 'message')'
      - name: check tag names
        if: ${{ endsWith(github.ref, 'message') != true }}
        run: echo 'endsWith(github.ref, 'message')'
